### ISSUE TITLE
Suggestion: nginx settings for securing Shiny server with SSL

### ISSUE THREAD

**Issue by adisarid** [TelethonKids/deploy_shiny_app#1]
Looks like a great tutorial on how to set Shiny on docker! 
I'll dive deep into it later on for sure!.

One small suggestion though, I noticed that the nginx configuration file is using ports 80 and port 8080 for shinyproxy. There are ways today to secure the connection using a reverse proxy to port 443 (there are even certificates that can be issued by Let's Encrypt, automatically and for free). I've done this in the past with a regular shiny server, but how would the nginx.conf file look like in this case if a secured connection is 
desired?

**Comment by pgstevenson** [comment]
Great point, which I'll be looking into later this week.
