### ISSUE TITLE
Deployment on a Google Cloud VM

### ISSUE THREAD

**Issue by Yves-Naly** [TelethonKids/deploy_shiny_app#6]
Hello @pgstevenson  ,

First I'd like to highlight that it's a very good tutorial.
I can now use my app locally.

Maybe it's a dumb question, but if I'd like to deploy it on a Google Cloud VM, is it still possible to use the different configuration files as is or not? (I'm thinking about the nginx.conf for example).
I'm asking this because I'm not really a devops and if it's too much job to do it, maybe I'd ask a more competent person to do this :)

Thanks in advance.

**Comment by pgstevenson** [comment]
@Yves-Naly I can't speak for Google Cloud VM, but I've used this repo for a couple of apps on an AWS EC2 instance.

**Comment by Yves-Naly** [comment]
Hi @pgstevenson , thanks for your reply.
It works as expected.
